// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-DgCv4VYE4baUqECHhZXHZeVY7aKpvGI',
    appId: '1:936049481100:web:97bca3f45d17ff6d3872a9',
    messagingSenderId: '936049481100',
    projectId: 'gsoft-biz-production',
    authDomain: 'gsoft-biz-production.firebaseapp.com',
    storageBucket: 'gsoft-biz-production.firebasestorage.app',
    measurementId: 'G-24WECGDQLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWwhn5TEYOlH4Wi64fW1IYRAd5-U30r40',
    appId: '1:936049481100:android:57aa74395ba5f56e3872a9',
    messagingSenderId: '936049481100',
    projectId: 'gsoft-biz-production',
    storageBucket: 'gsoft-biz-production.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pNMlk-N1tvcSzc7Vi70Y1kYkIIvxcrw',
    appId: '1:936049481100:ios:2240b7f0e36bceb33872a9',
    messagingSenderId: '936049481100',
    projectId: 'gsoft-biz-production',
    storageBucket: 'gsoft-biz-production.firebasestorage.app',
    iosBundleId: 'com.example.gsoftBiz',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8pNMlk-N1tvcSzc7Vi70Y1kYkIIvxcrw',
    appId: '1:936049481100:ios:2240b7f0e36bceb33872a9',
    messagingSenderId: '936049481100',
    projectId: 'gsoft-biz-production',
    storageBucket: 'gsoft-biz-production.firebasestorage.app',
    iosBundleId: 'com.example.gsoftBiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-DgCv4VYE4baUqECHhZXHZeVY7aKpvGI',
    appId: '1:936049481100:web:ccaf61033f8046a23872a9',
    messagingSenderId: '936049481100',
    projectId: 'gsoft-biz-production',
    authDomain: 'gsoft-biz-production.firebaseapp.com',
    storageBucket: 'gsoft-biz-production.firebasestorage.app',
    measurementId: 'G-MCM8MTKJVT',
  );
}
